apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: gidp-eva-infobip
  namespace: eva
  labels:
    app: gidp-eva-infobip
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gidp-eva-infobip
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
#    - type: Resource
#      resource:
#        name: memory
#        targetAverageUtilization: 80